name: Run pytests and build+publish docker container if tests pass

on:
  push:
    branches:
      - '**'  # Run on all branches

env:
  # GitHub container registry (could use dockerhub)
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: .
        
    strategy:
      matrix:
        # From tox.ini
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install napari[all]
          python -m pip install .[test]
          
      - name: Run Tests
        env:
          PLATFORM: ${{ matrix.platform }}
          QT_QPA_PLATFORM: offscreen
        run: |
          python -m pytest -vv test
          pkill -f python || true
          pkill -f napari || true


  # build-and-push:
  #   needs: test # tests must complete
  #   # Optional: Only build container if main or manually trigger
  #   #if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract metadata for image tags
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  #         tags: |
  #           type=ref,event=branch,suffix=-latest
  #           type=ref,event=branch,suffix=-{{sha}}
  #           type=raw,value=latest,enable={{is_default_branch}}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
          # push: true
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
